global.FLIGHT_BOOKING = 'FB';
global.DB_SAFE_SEPARATOR = '*_*';
global.SCHEDULER_RELOAD_TIME_LIMIT = 604800;
global.ACTIVE=1;
global.TRAIN_BOOKING = 'TB';
global.INACTIVE=0
global.META_TRAIN_COURSE = 'VHCID1420613777';
global.CURRENCY = 'INR';
global.TRAINNONACSERVICECHARGES=20;
global.TRAINACSERVICECHARGES=40;


